=== Ayushree-2147141/HMS-Patient-Module/DOM Parser/Appointment.xsd
<?xml version="1.0" encoding="UTF-8"?>
<hms:schema xmlns:hms="http://www.w3.org/2001/XMLSchema">
	<hms:element name="Appointment">
		<hms:complexType>
			<hms:sequence>
				<hms:element name="Patient" maxOccurs="unbounded">
					<hms:complexType>
						<hms:sequence>
						
							<hms:element name="Patient_name" type="hms:string"></hms:element>
							<hms:element name="Patient_id" type="hms:integer"></hms:element>
							<hms:element name="Doctor_name" type="hms:string"></hms:element>
							<hms:element name="Doctor_id" type="hms:integer"></hms:element>
							<hms:element name="Appointment_date" type="MyDate"></hms:element>
							<hms:element name="Appointment_time" type="MyTime"></hms:element>
							<hms:element name="Patient_gender" type="Gender"></hms:element>
							
						</hms:sequence>
					</hms:complexType>
				</hms:element>
			</hms:sequence>		
		</hms:complexType>
	</hms:element>
	<hms:simpleType name="MyTime">
		<hms:restriction base="hms:time">
			<hms:minInclusive value='07:00:00'></hms:minInclusive>
			<hms:maxInclusive value='19:00:00'></hms:maxInclusive>
		</hms:restriction>
	</hms:simpleType>
	
	<hms:simpleType name="Gender">
		<hms:restriction base="hms:string">
			<hms:pattern value="male|female"></hms:pattern>
		</hms:restriction>
	</hms:simpleType>
	
	<hms:simpleType name="MyDate">
		<hms:restriction base="hms:date">
			<hms:minInclusive value="1915-01-01"></hms:minInclusive>
		</hms:restriction>
	</hms:simpleType>
</hms:schema>

=== Ayushree-2147141/HMS-Patient-Module/Lab 5/Appointment.xml
<?xml version="1.0" encoding="UTF-8"?>
<Appointment xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="Appointment.xsd">

  <Patient>
    <Patient_name>Harshita Singh</Patient_name>
    <Patient_id>01</Patient_id>
    <Doctor_name>Dr. Manish Malhotra</Doctor_name>
    <Doctor_id>91</Doctor_id>
    <Appointment_date>2021-09-11</Appointment_date>
    <Appointment_time>13:00:00</Appointment_time>
    <Patient_gender>female</Patient_gender>
  </Patient>
  
  <Patient>
    <Patient_name>Prateek Kukkad</Patient_name>
    <Patient_id>02</Patient_id>
    <Doctor_name>Dr. Aishwarya Rai</Doctor_name>
    <Doctor_id>92</Doctor_id>
    <Appointment_date>2022-01-13</Appointment_date>
    <Appointment_time>10:30:00</Appointment_time>
    <Patient_gender>male</Patient_gender>
  </Patient>
  
  <Patient>
    <Patient_name>Kanika Arora</Patient_name>
    <Patient_id>03</Patient_id>
    <Doctor_name>Dr. Manish Malhotra</Doctor_name>
    <Doctor_id>91</Doctor_id>
    <Appointment_date>2022-10-12</Appointment_date>
    <Appointment_time>15:30:00</Appointment_time>
    <Patient_gender>female</Patient_gender>
  </Patient>
  
  <Patient>
    <Patient_name>Aastha Singhania</Patient_name>
    <Patient_id>04</Patient_id>
    <Doctor_name>Dr. Elizabeth Quith</Doctor_name>
    <Doctor_id>93</Doctor_id>
    <Appointment_date>2021-09-11</Appointment_date>
    <Appointment_time>13:00:00</Appointment_time>
    <Patient_gender>female</Patient_gender>
  </Patient>
  
  <Patient>
    <Patient_name>Yukta Singh</Patient_name>
    <Patient_id>05</Patient_id>
    <Doctor_name>Dr. Manish Malhotra</Doctor_name>
    <Doctor_id>91</Doctor_id>
    <Appointment_date>2022-01-12</Appointment_date>
    <Appointment_time>17:00:00</Appointment_time>
    <Patient_gender>female</Patient_gender>
  </Patient>
  
  <Patient>
    <Patient_name>Harshit Kumar</Patient_name>
    <Patient_id>06</Patient_id>
    <Doctor_name>Dr. AK Verma</Doctor_name>
    <Doctor_id>95</Doctor_id>
    <Appointment_date>2022-07-11</Appointment_date>
    <Appointment_time>18:00:00</Appointment_time>
    <Patient_gender>male</Patient_gender>
  </Patient>
</Appointment>
